zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
manager:
  image: sheepkiller/kafka-manager
  ports:
    - "9000:9000"
  links:
    - kafka
  environment:
    ZK_HOSTS: 192.168.59.103:2181
